# fly.toml app configuration file generated for short-weme-new on 2023-09-13T14:41:18-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "short-weme-new"
primary_region = "gru"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]